/**
 * Identity & Access — bounded context schema.
 *
 * See `docs/02-architecture/BOUNDED_CONTEXTS.md` → Identity & Access.
 *
 * RLS policies are written as raw SQL in the migration file generated by
 * `drizzle-kit`. Drizzle's `sql` template tag is used in this file for the
 * `pgcrypto` extension and the RLS policy SQL.
 */
import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  index,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/** A learning center — one row per tenant. */
export const tenants = pgTable(
  "tenants",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
  },
  (t) => ({
    slugUnique: uniqueIndex("tenants_slug_unique").on(t.slug),
  })
);

/** A user belongs to exactly one tenant. Role governs RBAC. */
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "restrict" }),
    email: text("email").notNull(), // normalized to lower-case; citext extension added in migration
    nationalId: text("national_id").notNull(), // 10-digit Iranian national ID — the login identifier
    passwordHash: text("password_hash").notNull(),
    displayName: text("display_name").notNull(),
    role: text("role").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    deactivatedAt: timestamp("deactivated_at", { withTimezone: true }),
  },
  (t) => ({
    tenantEmailUnique: uniqueIndex("users_tenant_email_unique").on(t.tenantId, t.email),
    tenantNationalIdUnique: uniqueIndex("users_tenant_national_id_unique").on(
      t.tenantId,
      t.nationalId
    ),
    tenantIdx: index("users_tenant_idx").on(t.tenantId),
    roleCheck: check(
      "users_role_check",
      sql`${t.role} in ('super_admin','center_admin','teacher','student')`
    ),
  })
);

export type Tenant = typeof tenants.$inferSelect;
export type NewTenant = typeof tenants.$inferInsert;
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Role = "super_admin" | "center_admin" | "teacher" | "student";
